const {cmd , commands} = require('../command');

cmd({
    pattern: "love100",
    desc: "SEND 100 TYMES LOVE",
    category: "fun",
    react: "👨‍💻",
    filename: __filename
},
async (conn, mek, m, { from, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    try {
        const steps = [
            '*I LOVE YOU....🌹💝*',
          '*I LOVE YOU....🌹💝*',
          '*I LOVE YOU....🌹💝*',
  '*I LOVE YOU....🌹💝*',
 '*I LOVE YOU....🌹💝*',
  '*I LOVE YOU....🌹💝*',
  '*I LOVE YOU....🌹💝*',
  '*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
'*I LOVE YOU....🌹💝*',
             '*I LOVE YOU....🌹💝*'
        ];

        for (const line of steps) {
            await conn.sendMessage(from, { text: line }, { quoted: mek });
            await new Promise(resolve => setTimeout(resolve, 1000)); // Adjust the delay as needed
        }
    } catch (e) {
        console.log(e);
        reply(`❌ *Error!* ${e.message}`);
    }
});
